import "./globals.css";
import { Inter, Roboto, Poppins } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import ThemeProvider, { ThemeContext } from "@/context/ThemeContext";
import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Agency WebApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className`}>
          <ThemeProvider>
            <Navbar />
            {children}
            {/* <Footer /> */}
          </ThemeProvider>
      </body>
    </html>
  );
}
